service: import-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource: 'arn:aws:s3:::import-services-bucket/*'
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource: 'arn:aws:s3:::import-services-bucket/*'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-services-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
